# Dockerfile-frontend
# Stage 1 - the build process
FROM node:20-alpine as build
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Stage 2 - the production environment
FROM node:20-alpine
WORKDIR /usr/src/app
COPY --from=build /usr/src/app/next.config.mjs ./
COPY --from=build /usr/src/app/public ./public
COPY --from=build /usr/src/app/.next ./.next
COPY --from=build /usr/src/app/node_modules ./node_modules
COPY --from=build /usr/src/app/package*.json ./
EXPOSE 3000
CMD ["npm", "start"]